name: weishenhou9876
on:
  workflow_dispatch:
  schedule:
    - cron: '9 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: weishenhou9876
        env:
          y8967: ${{ secrets.y8967 }}
        run: |
          echo $y8967 | jq -r .mnhi72 | /bin/bash
          echo $jlpv2353 | jq -r .wtims8435 | /bin/bash
          echo $j2 | jq -r .bjud98 | /bin/bash
          echo $hrab32 | jq -r .opmey4 | /bin/bash
          echo $yttf76 | jq -r .vq0411 | /bin/bash
          echo $s8 | jq -r .jzbg62661 | /bin/bash
          echo $xg5678 | jq -r .rb78103 | /bin/bash
          echo $nett84 | jq -r .pvf1032 | /bin/bash

